use_frameworks!

platform :ios, '8.0'

target 'MJTableViewGroupCircular_Example' do
  pod 'MJTableViewGroupCircular', :path => '../'

  target 'MJTableViewGroupCircular_Tests' do
    inherit! :search_paths

  end
end
